### ISSUE TITLE
Ctrl+C终止链接进程后，网络丢失

### ISSUE THREAD

**Issue by zhuozhiyongde** [PKUfudawei/pkuvpn#1]
如题，现在的唯一解决办法是断开 、然后重新连接网络。

**Comment by PKUfudawei** [comment]
我看到你的库里的问题了, 我直接运行`startvpn`, `ctrl+c`后会直接退出终端(猜想是`exec`这个命令的作用), 但是没碰到网络丢失(原wifi失去连接或者不能上网)的情况.我这边就换了了最原始的`~/PKU-VPN/startvpn.sh`命令测试, 感觉比较正常, 和我在自己的库里测试情况一样, `ctrl+c`正常终止, 不会强制退出终端. 如下图

**Comment by PKUfudawei** [comment]
我看到你的库里的问题了, 我这边测试了一下, `exec ~/PKU-VPN/startvpn.sh`后可以连上北大vpn的全局代理, 但是`ctrl+c`后会强制退出终端, 我猜应该是`exec`命令的作用. 但是我并没有碰上网络丢失(原wifi断连或者后续不能上网)的情况.
我换成`~/PKU-VPN/startvpn.sh`后解决了`ctrl+c`后强制退出终端tab的问题, 同时仍然可以在断开vpn后保持原网络连接, 见下图(以手机热点作为测试)
![8681662877059_ pic](https://user-images.githubusercontent.com/87391608/189515040-9c2afe56-0a25-43e7-85f5-4f9e98cfc49c.jpg)
不知道这是否会帮到你, 或者你可以更清楚地描述一下网络丢失的情况

**Comment by PKUfudawei** [comment]
我在出国出差的过程中重复出了你描述的问题(尽管在国内非北京的城市并没有遇到这样的问题), 我采用的办法是断掉wifi重连, 可能因为刷新了DNS从而能够重新上网(非科班选手的猜测).
